// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Get configuration from runtime config if available, otherwise use environment variables or fallbacks
const getRuntimeConfig = () => {
  if (typeof window !== 'undefined' && window.ENV) {
    return {
      supabaseUrl: window.ENV.SUPABASE_URL,
      supabaseKey: window.ENV.SUPABASE_ANON_KEY
    };
  }
  return {
    supabaseUrl: import.meta.env.VITE_SUPABASE_URL || "https://okzcrijmvpwouqemvzat.supabase.co",
    supabaseKey: import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9remNyaWptdnB3b3VxZW12emF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ0ODE2MDksImV4cCI6MjAzMDA1NzYwOX0.h5yjY7nOvvSFsNiRxH69WzQhGl8kyGvzYUcYe6z-WGE"
  };
};

const config = getRuntimeConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(config.supabaseUrl, config.supabaseKey);

// For debugging
console.log('Supabase URL:', config.supabaseUrl);
console.log('Supabase client initialized');