// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use environment variables with fallbacks to hardcoded values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://okzcrijmvpwouqemvzat.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9remNyaWptdnB3b3VxZW12emF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ0ODE2MDksImV4cCI6MjAzMDA1NzYwOX0.h5yjY7nOvvSFsNiRxH69WzQhGl8kyGvzYUcYe6z-WGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);